#!/bin/bash
# init-project.sh — Initialize .inspirai/ directory in current project
# Creates project-level config and handoffs directory
#
# Usage: bash init-project.sh [--force]
#   --force  Re-initialize even if .inspirai/ exists

set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

FORCE=false
[[ "${1:-}" == "--force" ]] && FORCE=true

# --- Guard: already initialized ---
if [[ -d ".inspirai" ]] && ! $FORCE; then
  echo -e "${YELLOW}⚠${NC} .inspirai/ already exists. Use --force to re-initialize."
  exit 0
fi

# --- Create structure ---
mkdir -p .inspirai/handoffs

# --- config.yaml ---
if [[ ! -f ".inspirai/config.yaml" ]] || $FORCE; then
  cat > .inspirai/config.yaml <<'YAML'
# Inspirai Dev Mode - Project Configuration
# Generated by inspirai-mode plugin

# Execution routing: which CLI handles which task type
routing:
  backend: claude-code
  design: claude-code      # Pencil MCP for UI, Claude Code for system design
  deploy: claude-code
  infra: claude-code
  frontend: gemini-cli

# Pencil MCP: always used for UI/interaction design before frontend code
pencil:
  required_before_frontend: true

# Handoff format
handoff:
  format: markdown
  directory: .inspirai/handoffs
YAML
fi

# --- state.json ---
if [[ ! -f ".inspirai/state.json" ]] || $FORCE; then
  cat > .inspirai/state.json <<JSON
{
  "initialized_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "initialized_by": "$(basename "${CLAUDE_PLUGIN_ROOT:-inspirai-mode}")",
  "current_phase": null,
  "last_handoff": null
}
JSON
fi

# --- .gitignore entry ---
if [[ -f ".gitignore" ]]; then
  if ! grep -q "^\.inspirai/state\.json" .gitignore 2>/dev/null; then
    echo "" >> .gitignore
    echo "# inspirai-mode runtime state" >> .gitignore
    echo ".inspirai/state.json" >> .gitignore
  fi
fi

echo -e "${GREEN}✓${NC} .inspirai/ initialized"
echo "  ├── config.yaml    (routing config — commit this)"
echo "  ├── state.json     (runtime state — gitignored)"
echo "  └── handoffs/      (cross-CLI task handoffs)"
